DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  TO_BGR255: False
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "output/keypoint_rcnn_hrnet_w18_1x_20210202"
  BACKBONE:
    CONV_BODY: "HRNET-FPN"
    OUT_CHANNELS: 256
  NECK:
    IN_CHANNELS:
      - 18
      - 36
      - 72
      - 144
    OUT_CHANNELS: 256
    POOLING: "AVG"
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  HRNET:
    STAGE1:
      NUM_CHANNELS:
      - 64
      NUM_BLOCKS:
      - 4
      BLOCK: 'BottleneckWithFixedBatchNorm'
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 18
      - 36
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 18
      - 36
      - 72
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS: 
      - 18
      - 36
      - 72
      - 144
      BLOCK: 'BasicBlockWithFixedBatchNorm'
      FUSE_METHOD: 'SUM'
    DECODER:
      BLOCK: 'BottleneckWithFixedBatchNorm'
      HEAD_UPSAMPLING: 'BILINEAR'
      HEAD_UPSAMPLING_KERNEL: 1
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
  KEYPOINT_ON: True
DATASETS:
  TRAIN: ("keypoints_coco_2017_train", "keypoints_coco_2017_val",)
  TEST: ("keypoints_coco_2017_val",)
SOLVER:
  BASE_LR: 0.0005
  WEIGHT_DECAY: 0.00001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 2
OUTPUT_DIR: "output/keypoint_rcnn_hrnet_w18_1x_20210202"  #_20210202
TEST:
  IMS_PER_BATCH: 1